(ns ucie_chiplet.actor-test
  "Contract test for the ucie_chiplet-compat L4 actor (Clojure / kotoba-Datom).
  Runs on bb / clojure with classpath = src:tests. Generated by
  70-tools/scaffold_wave11_clj_datomic.py."
  (:require [clojure.test :refer [deftest is testing run-tests]]
            [clojure.string :as str]
            [ucie_chiplet.actor :as a]))

(def ENTITIES ["Chiplet" "UcieLink" "BumpArray" "Sideband" "ProtocolLayer" "Package"])

(deftest schema-has-all-entities
  (doseq [e ENTITIES]
    (is (some (fn [d] (str/starts-with? (str (:db/ident d)) (str ":ucie_chiplet." e "/"))) a/schema)
        (str "schema missing entity " e))))

(deftest entities-set-complete
  (is (= (set ENTITIES) a/entities)))

(deftest crud-roundtrip
  (testing "Chiplet create/get/list/update/delete over in-memory Datom log"
    (let [port (a/in-memory-datom)
          rec  (a/create-chiplet port {:name "x" :function "x"})]
      (is (string? (:db/id rec)) "create returns a :db/id")
      (is (= rec (a/get-chiplet port (:db/id rec))) "get round-trips the record")
      (is (= 1 (:total (a/list-chiplets port))) "list total counts the created record")
      (let [up (a/update-chiplet port (:db/id rec) {:name "updated"})]
        (is (= "updated" (get up :ucie_chiplet.Chiplet/name)) "update applies the changed field"))
      (a/delete-chiplet port (:db/id rec))
      (is (= 0 (:total (a/list-chiplets port))) "delete removes the record"))))

(deftest list-filter-and-paginate
  (testing "L4 list surface: filtering + cursor pagination"
    (let [port (a/in-memory-datom)
          _ (a/create-chiplet port {:name "x" :function "x"})
          _ (a/create-chiplet port {:name "y" :function "x"})]
      (is (= 2 (:total (a/list-chiplets port))) "both records listed")
      (is (true? (:has-more (a/list-chiplets port {:limit 1}))) "limit drives has-more")
      (is (= 1 (:count (a/list-chiplets port {:limit 1}))) "limit caps the page")
      (is (= 1 (:total (a/list-chiplets port {:filter {:ucie_chiplet.Chiplet/name "x"}})))
          "filter narrows to the matching record"))))

(deftest validation-rejects-missing-required
  (is (thrown? #?(:clj clojure.lang.ExceptionInfo :cljs cljs.core/ExceptionInfo)
               (a/create-chiplet (a/in-memory-datom) {}))
      "create with no required fields throws"))

;; every entity collection (not just the first) → full lifecycle via dispatch
(def SAMPLES {"chiplets" {:name "x" :function "x"}
   "ucielinks" {:mode "x" :lanes "x"}
   "bumparrays" {:pitchUm "x" :count "x"}
   "sidebands" {:function "x" :frequencyMhz "x"}
   "protocollayers" {:protocol "x" :flitFormat "x"}
   "packages" {:name "x" :substrate "x"}})

(deftest all-collections-crud
  (testing "every entity collection runs the full lifecycle through dispatch"
    (doseq [[coll sample] SAMPLES]
      (let [port    (a/in-memory-datom)
            base    (str "/v1/" coll)
            created (a/dispatch port {:method :post :path base :body sample})
            id      (get-in created [:body :db/id])]
        (is (= 201 (:status created)) (str coll " POST → 201"))
        (is (string? id) (str coll " create body carries :db/id"))
        (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)})))
            (str coll " GET one → 200"))
        (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " list total 1"))
        (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)})))
            (str coll " DELETE → 200"))
        (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " empty after delete"))))))

(deftest dispatch-end-to-end
  (testing "runnable service surface: create→get→list→update→delete through dispatch"
    (let [port (a/in-memory-datom)
          base "/v1/chiplets"
          created (a/dispatch port {:method :post :path base :body {:name "x" :function "x"}})
          id (get-in created [:body :db/id])]
      (is (= 201 (:status created)) "POST creates → 201")
      (is (string? id) "create body carries :db/id")
      (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)}))) "GET one → 200")
      (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "GET list → total 1")
      (is (= 404 (:status (a/dispatch port {:method :get :path (str base "/nope")}))) "GET absent → 404")
      (let [upd (a/dispatch port {:method :patch :path (str base "/" id) :body {:name "updated"}})]
        (is (= 200 (:status upd)) "PATCH → 200")
        (is (= "updated" (get-in upd [:body :ucie_chiplet.Chiplet/name])) "PATCH applies the field"))
      (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)}))) "DELETE → 200")
      (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "list empty after delete")
      (is (= 404 (:status (a/dispatch port {:method :get :path "/v1/bogus"}))) "unknown collection → 404"))))

(deftest expand-inlines-relation
  (testing "?expand inlines the referenced Chiplet on a UcieLink"
    (let [port   (a/in-memory-datom)
          parent (a/create-chiplet port {:name "x" :function "x"})
          child  (a/create-ucie-link port (assoc {:mode "x" :lanes "x"} :chipletId (:db/id parent)))
          got    (a/get-ucie-link port (:db/id child) {:expand #{:chipletId}})]
      (is (= (:db/id parent) (:db/id (:chipletId-obj got)))
          "expand resolves the relation to the parent entity"))))

(defn -main [& _]
  (let [{:keys [fail error]} (run-tests 'ucie_chiplet.actor-test)]
    (System/exit (if (pos? (+ (or fail 0) (or error 0))) 1 0))))
