(ns ucie_chiplet.actor
  "ucie_chiplet clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). UCIe chiplet die-to-die interconnect / advanced packaging.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Chiplet
   {:db/ident :ucie_chiplet.Chiplet/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.Chiplet/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Chiplet/function :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Chiplet/processNode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Chiplet/areaMm2 :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Chiplet/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Chiplet/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; UcieLink
   {:db/ident :ucie_chiplet.UcieLink/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.UcieLink/chipletId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.UcieLink/mode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.UcieLink/lanes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.UcieLink/dataRateGtps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.UcieLink/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.UcieLink/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; BumpArray
   {:db/ident :ucie_chiplet.BumpArray/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.BumpArray/chipletId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.BumpArray/pitchUm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.BumpArray/count :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.BumpArray/bumpType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.BumpArray/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.BumpArray/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Sideband
   {:db/ident :ucie_chiplet.Sideband/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.Sideband/linkId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Sideband/function :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Sideband/frequencyMhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Sideband/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Sideband/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ProtocolLayer
   {:db/ident :ucie_chiplet.ProtocolLayer/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.ProtocolLayer/linkId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.ProtocolLayer/protocol :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.ProtocolLayer/flitFormat :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.ProtocolLayer/retimer :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.ProtocolLayer/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.ProtocolLayer/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Package
   {:db/ident :ucie_chiplet.Package/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :ucie_chiplet.Package/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Package/substrate :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Package/chipletCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Package/interposer :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Package/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :ucie_chiplet.Package/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Chiplet" "UcieLink" "BumpArray" "Sideband" "ProtocolLayer" "Package"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "ucie_chiplet: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "ucie_chiplet: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "ucie_chiplet: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Chiplet ────────────────────────────────────────────────────────────────
(defn create-chiplet
  "Create a Chiplet."
  [port data]
  (require-fields data ["name" "function"])
  (let [id (new-id "ucie_chi")
        e {:db/id id
           :ucie_chiplet.Chiplet/id id
           :ucie_chiplet.Chiplet/name (get data :name)
           :ucie_chiplet.Chiplet/function (get data :function)
           :ucie_chiplet.Chiplet/processNode (get data :processNode)
           :ucie_chiplet.Chiplet/areaMm2 (as-double (get data :areaMm2))
           :ucie_chiplet.Chiplet/createdAt (now)
           :ucie_chiplet.Chiplet/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-chiplets
  "List Chiplet with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-chiplets port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.Chiplet/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.Chiplet/name :ucie_chiplet.Chiplet/function :ucie_chiplet.Chiplet/processNode :ucie_chiplet.Chiplet/areaMm2])]
     (paginate rows opts))))

(defn get-chiplet
  "Retrieve a Chiplet by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-chiplet port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-chiplet
  "Update a Chiplet; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :ucie_chiplet.Chiplet/name (get data :name)]))
                   (cond-> (contains? data :function) (conj [:db/add id :ucie_chiplet.Chiplet/function (get data :function)]))
                   (cond-> (contains? data :processNode) (conj [:db/add id :ucie_chiplet.Chiplet/processNode (get data :processNode)]))
                   (cond-> (contains? data :areaMm2) (conj [:db/add id :ucie_chiplet.Chiplet/areaMm2 (as-double (get data :areaMm2))]))
                   (conj [:db/add id :ucie_chiplet.Chiplet/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-chiplet
  "Delete a Chiplet."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── UcieLink ────────────────────────────────────────────────────────────────
(defn create-ucie-link
  "Create a UcieLink."
  [port data]
  (require-fields data ["mode" "lanes"])
  (let [id (new-id "ucie_uci")
        e {:db/id id
           :ucie_chiplet.UcieLink/id id
           :ucie_chiplet.UcieLink/chipletId (get data :chipletId)
           :ucie_chiplet.UcieLink/mode (get data :mode)
           :ucie_chiplet.UcieLink/lanes (as-long (get data :lanes))
           :ucie_chiplet.UcieLink/dataRateGtps (as-double (get data :dataRateGtps))
           :ucie_chiplet.UcieLink/createdAt (now)
           :ucie_chiplet.UcieLink/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-ucie-links
  "List UcieLink with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-ucie-links port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.UcieLink/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.UcieLink/chipletId :ucie_chiplet.UcieLink/mode :ucie_chiplet.UcieLink/lanes :ucie_chiplet.UcieLink/dataRateGtps])]
     (paginate rows opts))))

(defn get-ucie-link
  "Retrieve a UcieLink by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-ucie-link port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :chipletId) (get rec :ucie_chiplet.UcieLink/chipletId))
         (assoc :chipletId-obj (-pull port (get rec :ucie_chiplet.UcieLink/chipletId))))))))

(defn update-ucie-link
  "Update a UcieLink; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :chipletId) (conj [:db/add id :ucie_chiplet.UcieLink/chipletId (get data :chipletId)]))
                   (cond-> (contains? data :mode) (conj [:db/add id :ucie_chiplet.UcieLink/mode (get data :mode)]))
                   (cond-> (contains? data :lanes) (conj [:db/add id :ucie_chiplet.UcieLink/lanes (as-long (get data :lanes))]))
                   (cond-> (contains? data :dataRateGtps) (conj [:db/add id :ucie_chiplet.UcieLink/dataRateGtps (as-double (get data :dataRateGtps))]))
                   (conj [:db/add id :ucie_chiplet.UcieLink/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-ucie-link
  "Delete a UcieLink."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── BumpArray ────────────────────────────────────────────────────────────────
(defn create-bump-array
  "Create a BumpArray."
  [port data]
  (require-fields data ["pitchUm" "count"])
  (let [id (new-id "ucie_bum")
        e {:db/id id
           :ucie_chiplet.BumpArray/id id
           :ucie_chiplet.BumpArray/chipletId (get data :chipletId)
           :ucie_chiplet.BumpArray/pitchUm (as-double (get data :pitchUm))
           :ucie_chiplet.BumpArray/count (as-long (get data :count))
           :ucie_chiplet.BumpArray/bumpType (get data :bumpType)
           :ucie_chiplet.BumpArray/createdAt (now)
           :ucie_chiplet.BumpArray/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-bump-arrays
  "List BumpArray with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-bump-arrays port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.BumpArray/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.BumpArray/chipletId :ucie_chiplet.BumpArray/pitchUm :ucie_chiplet.BumpArray/count :ucie_chiplet.BumpArray/bumpType])]
     (paginate rows opts))))

(defn get-bump-array
  "Retrieve a BumpArray by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-bump-array port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :chipletId) (get rec :ucie_chiplet.BumpArray/chipletId))
         (assoc :chipletId-obj (-pull port (get rec :ucie_chiplet.BumpArray/chipletId))))))))

(defn update-bump-array
  "Update a BumpArray; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :chipletId) (conj [:db/add id :ucie_chiplet.BumpArray/chipletId (get data :chipletId)]))
                   (cond-> (contains? data :pitchUm) (conj [:db/add id :ucie_chiplet.BumpArray/pitchUm (as-double (get data :pitchUm))]))
                   (cond-> (contains? data :count) (conj [:db/add id :ucie_chiplet.BumpArray/count (as-long (get data :count))]))
                   (cond-> (contains? data :bumpType) (conj [:db/add id :ucie_chiplet.BumpArray/bumpType (get data :bumpType)]))
                   (conj [:db/add id :ucie_chiplet.BumpArray/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-bump-array
  "Delete a BumpArray."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Sideband ────────────────────────────────────────────────────────────────
(defn create-sideband
  "Create a Sideband."
  [port data]
  (require-fields data ["function" "frequencyMhz"])
  (let [id (new-id "ucie_sid")
        e {:db/id id
           :ucie_chiplet.Sideband/id id
           :ucie_chiplet.Sideband/linkId (get data :linkId)
           :ucie_chiplet.Sideband/function (get data :function)
           :ucie_chiplet.Sideband/frequencyMhz (as-double (get data :frequencyMhz))
           :ucie_chiplet.Sideband/createdAt (now)
           :ucie_chiplet.Sideband/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-sidebands
  "List Sideband with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-sidebands port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.Sideband/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.Sideband/linkId :ucie_chiplet.Sideband/function :ucie_chiplet.Sideband/frequencyMhz])]
     (paginate rows opts))))

(defn get-sideband
  "Retrieve a Sideband by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sideband port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-sideband
  "Update a Sideband; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :linkId) (conj [:db/add id :ucie_chiplet.Sideband/linkId (get data :linkId)]))
                   (cond-> (contains? data :function) (conj [:db/add id :ucie_chiplet.Sideband/function (get data :function)]))
                   (cond-> (contains? data :frequencyMhz) (conj [:db/add id :ucie_chiplet.Sideband/frequencyMhz (as-double (get data :frequencyMhz))]))
                   (conj [:db/add id :ucie_chiplet.Sideband/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sideband
  "Delete a Sideband."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ProtocolLayer ────────────────────────────────────────────────────────────────
(defn create-protocol-layer
  "Create a ProtocolLayer."
  [port data]
  (require-fields data ["protocol" "flitFormat"])
  (let [id (new-id "ucie_pro")
        e {:db/id id
           :ucie_chiplet.ProtocolLayer/id id
           :ucie_chiplet.ProtocolLayer/linkId (get data :linkId)
           :ucie_chiplet.ProtocolLayer/protocol (get data :protocol)
           :ucie_chiplet.ProtocolLayer/flitFormat (get data :flitFormat)
           :ucie_chiplet.ProtocolLayer/retimer (as-bool (get data :retimer))
           :ucie_chiplet.ProtocolLayer/createdAt (now)
           :ucie_chiplet.ProtocolLayer/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-protocol-layers
  "List ProtocolLayer with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-protocol-layers port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.ProtocolLayer/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.ProtocolLayer/linkId :ucie_chiplet.ProtocolLayer/protocol :ucie_chiplet.ProtocolLayer/flitFormat :ucie_chiplet.ProtocolLayer/retimer])]
     (paginate rows opts))))

(defn get-protocol-layer
  "Retrieve a ProtocolLayer by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-protocol-layer port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-protocol-layer
  "Update a ProtocolLayer; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :linkId) (conj [:db/add id :ucie_chiplet.ProtocolLayer/linkId (get data :linkId)]))
                   (cond-> (contains? data :protocol) (conj [:db/add id :ucie_chiplet.ProtocolLayer/protocol (get data :protocol)]))
                   (cond-> (contains? data :flitFormat) (conj [:db/add id :ucie_chiplet.ProtocolLayer/flitFormat (get data :flitFormat)]))
                   (cond-> (contains? data :retimer) (conj [:db/add id :ucie_chiplet.ProtocolLayer/retimer (as-bool (get data :retimer))]))
                   (conj [:db/add id :ucie_chiplet.ProtocolLayer/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-protocol-layer
  "Delete a ProtocolLayer."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Package ────────────────────────────────────────────────────────────────
(defn create-package
  "Create a Package."
  [port data]
  (require-fields data ["name" "substrate"])
  (let [id (new-id "ucie_pac")
        e {:db/id id
           :ucie_chiplet.Package/id id
           :ucie_chiplet.Package/name (get data :name)
           :ucie_chiplet.Package/substrate (get data :substrate)
           :ucie_chiplet.Package/chipletCount (as-long (get data :chipletCount))
           :ucie_chiplet.Package/interposer (get data :interposer)
           :ucie_chiplet.Package/createdAt (now)
           :ucie_chiplet.Package/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-packages
  "List Package with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-packages port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :ucie_chiplet.Package/id))
         rows (apply-filters rows (:filter opts) [:ucie_chiplet.Package/name :ucie_chiplet.Package/substrate :ucie_chiplet.Package/chipletCount :ucie_chiplet.Package/interposer])]
     (paginate rows opts))))

(defn get-package
  "Retrieve a Package by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-package port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-package
  "Update a Package; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :ucie_chiplet.Package/name (get data :name)]))
                   (cond-> (contains? data :substrate) (conj [:db/add id :ucie_chiplet.Package/substrate (get data :substrate)]))
                   (cond-> (contains? data :chipletCount) (conj [:db/add id :ucie_chiplet.Package/chipletCount (as-long (get data :chipletCount))]))
                   (cond-> (contains? data :interposer) (conj [:db/add id :ucie_chiplet.Package/interposer (get data :interposer)]))
                   (conj [:db/add id :ucie_chiplet.Package/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-package
  "Delete a Package."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/chiplets" :op :create :entity "Chiplet"}
   {:method "GET" :path "/v1/chiplets" :op :list :entity "Chiplet"}
   {:method "GET" :path "/v1/chiplets/:id" :op :get :entity "Chiplet"}
   {:method "PATCH" :path "/v1/chiplets/:id" :op :update :entity "Chiplet"}
   {:method "DELETE" :path "/v1/chiplets/:id" :op :delete :entity "Chiplet"}
   {:method "POST" :path "/v1/ucielinks" :op :create :entity "UcieLink"}
   {:method "GET" :path "/v1/ucielinks" :op :list :entity "UcieLink"}
   {:method "GET" :path "/v1/ucielinks/:id" :op :get :entity "UcieLink"}
   {:method "PATCH" :path "/v1/ucielinks/:id" :op :update :entity "UcieLink"}
   {:method "DELETE" :path "/v1/ucielinks/:id" :op :delete :entity "UcieLink"}
   {:method "POST" :path "/v1/bumparrays" :op :create :entity "BumpArray"}
   {:method "GET" :path "/v1/bumparrays" :op :list :entity "BumpArray"}
   {:method "GET" :path "/v1/bumparrays/:id" :op :get :entity "BumpArray"}
   {:method "PATCH" :path "/v1/bumparrays/:id" :op :update :entity "BumpArray"}
   {:method "DELETE" :path "/v1/bumparrays/:id" :op :delete :entity "BumpArray"}
   {:method "POST" :path "/v1/sidebands" :op :create :entity "Sideband"}
   {:method "GET" :path "/v1/sidebands" :op :list :entity "Sideband"}
   {:method "GET" :path "/v1/sidebands/:id" :op :get :entity "Sideband"}
   {:method "PATCH" :path "/v1/sidebands/:id" :op :update :entity "Sideband"}
   {:method "DELETE" :path "/v1/sidebands/:id" :op :delete :entity "Sideband"}
   {:method "POST" :path "/v1/protocollayers" :op :create :entity "ProtocolLayer"}
   {:method "GET" :path "/v1/protocollayers" :op :list :entity "ProtocolLayer"}
   {:method "GET" :path "/v1/protocollayers/:id" :op :get :entity "ProtocolLayer"}
   {:method "PATCH" :path "/v1/protocollayers/:id" :op :update :entity "ProtocolLayer"}
   {:method "DELETE" :path "/v1/protocollayers/:id" :op :delete :entity "ProtocolLayer"}
   {:method "POST" :path "/v1/packages" :op :create :entity "Package"}
   {:method "GET" :path "/v1/packages" :op :list :entity "Package"}
   {:method "GET" :path "/v1/packages/:id" :op :get :entity "Package"}
   {:method "PATCH" :path "/v1/packages/:id" :op :update :entity "Package"}
   {:method "DELETE" :path "/v1/packages/:id" :op :delete :entity "Package"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"chiplets" {:create create-chiplet :list list-chiplets :get get-chiplet :update update-chiplet :delete delete-chiplet}
   "ucielinks" {:create create-ucie-link :list list-ucie-links :get get-ucie-link :update update-ucie-link :delete delete-ucie-link}
   "bumparrays" {:create create-bump-array :list list-bump-arrays :get get-bump-array :update update-bump-array :delete delete-bump-array}
   "sidebands" {:create create-sideband :list list-sidebands :get get-sideband :update update-sideband :delete delete-sideband}
   "protocollayers" {:create create-protocol-layer :list list-protocol-layers :get get-protocol-layer :update update-protocol-layer :delete delete-protocol-layer}
   "packages" {:create create-package :list list-packages :get get-package :update update-package :delete delete-package}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "ucie_chiplet-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
